# Generated by Django 2.2.6 on 2020-02-05 17:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_description', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ISBN', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('publishing_year', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in SGD', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image', pyuploadcare.dj.models.ImageField(null=True)),
                ('author', models.ManyToManyField(help_text='Select an author.', to='Catalog.Author')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book.', to='Catalog.Genre')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogues',
            },
        ),
    ]
