# Generated by Django 2.2.6 on 2020-02-15 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
        ('Order', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_number_token',
            new_name='stripe_token',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_payment',
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='Processing', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Catalog.Book')),
            ],
        ),
    ]
