# Generated by Django 2.2.6 on 2020-02-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20200224_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='county',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='town_or_city',
        ),
    ]
