# Generated by Django 2.2.6 on 2020-02-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20200224_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Singapore', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(default='Singapore', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=123456, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='123 Main AVe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(default='Singapore', max_length=50),
            preserve_default=False,
        ),
    ]
